### ISSUE TITLE
Show interval names in Note Distance Game (feature request)

### ISSUE THREAD

**Issue by apaatsio** [ryanatkn/ear-sharpener#1]
It would be useful to show the interval names (minor 2nd, perfect 5th, octave, etc) in addition to the number of semitones.

**Comment by ryanatkn** [comment]
Thanks for the suggestion. I don't know much about music theory - is [this](https://en.wikipedia.org/wiki/Interval_%28music%29#Size_of_intervals_used_in_different_tuning_systems) the full list? What do you call them when they are more than a full octave (13+ semitones) above? There's not a lot of space for text but I think I can make it work.

**Comment by apaatsio** [comment]
That list is correct. You can use abbreviations if the space is scarce: P1, m2, M2, m3, M3, P4, A4/d5, P5, m6, M6, m7, M7, P8.

After that the pattern starts over but you just increase the number: 13 = minor ninth / m9, 14 = major ninth / M9, 15 = minor tenth / m10, 16 = major tenth / M10, 17 = perfect eleventh / P11...

**Comment by ryanatkn** [comment]
Thanks for all of the info. I added the interval names using the abbreviations.
